/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_changfan_BsPatchUtility */

#ifndef _Included_com_example_changfan_BsPatchUtility
#define _Included_com_example_changfan_BsPatchUtility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_changfan_BsPatchUtility
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_changfan_BsPatchUtility_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
